# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SyMoCADS
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Over the past decade, Molecular Communications (MC) has emerged as a new research area in Communications. The main idea behind MC is to exploit molecules as information carriers, as is done in many natural communication processes including inter- and intracellular communication, synaptic communication, quorum sensing, and insect communication, to communicate in environments and with objects/organisms that are not suitable for conventional electromagnetic wave based communication systems. Synthetic MC systems are expected to enable new disruptive medical, environmental, and industrial applications. The objective of the proposed research training group "Synthetic Molecular Communication Across Different Scales: From Theory to Experiments (SyMoCADS)" is to establish the first structured doctoral training program on MC worldwide and to equip the participating doctoral students with the knowledge and skill set needed to advance this emerging interdisciplinary field of research. To this end, a multi-facetted research and qualification program will be established. To balance the inherent heterogeneity of the overall topic and the need for close interdisciplinary collaboration to tackle MC research problems, the doctoral research projects are organized in three clusters (C1-C3): C1: MC based design, monitoring, and control of bioprocesses; C2: MC based modelling, analysis, and design of magnetic nanoparticle steering systems; C3: Models, designs, and system architectures for airborne MC. Each cluster investigates an important and challenging overarching research problem, whose conceptual, communication-theoretical, and experimental aspects are tackled synergistically in three doctoral projects. This promotes close interdisciplinary collaboration between the doctoral students within each cluster, which constitutes a vital part of their training. The different clusters reflect the heterogeneity of MC in terms of length scales, particle transport mechanisms, propagation environments, communication tasks, experimental techniques, and application domains. This provides the opportunity to investigate the implications of these differences for MC analysis, modelling, and simulation techniques as well as for the embedding of information into molecular signals. The conceptual and methodical support needed for addressing these cross-cluster research questions, exploiting cross-cluster synergies, and fostering cross-cluster collaboration will be provided by a postdoctoral project. SyMoCADS is led by an interdisciplinary team of researchers who were carefully selected to foster fundamental theoretical and experimental contributions to each of the three cluster topics and the general field of MC.
baseurl: "" # the subpath of your site, e.g. /blog

domain: bahe007.github.io
url: "https://bahe007.github.io" 


# Build settings
#theme: minima

remote-theme: bahe007/rtg-rdm-website-theme
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
